# Generated by Django 3.2.25 on 2024-08-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_category_name_alter_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Ціна')),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Опис')),
                ('image', models.ImageField(default='', upload_to='uploads/master/', verbose_name='Загрузити фото')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Послуга')),
                ('image', models.ImageField(default='', upload_to='uploads/service/', verbose_name='Загрузити фото')),
            ],
        ),
        migrations.CreateModel(
            name='SinkFromTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Раковина з плитки')),
                ('image', models.ImageField(default='', upload_to='uploads/sinkFromTile/', verbose_name='Загрузити фото')),
            ],
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/product/', verbose_name='Загрузити фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/product/', verbose_name='Загрузити фото'),
        ),
    ]
