# Generated by Django 4.2.5 on 2024-06-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_imggal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imggal',
            name='imgdesc',
            field=models.CharField(max_length=20),
        ),
    ]
