# Generated by Django 4.2 on 2023-08-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Введіть ваше імя (обовязково)')),
                ('email', models.EmailField(max_length=254, verbose_name='Введіть ваш e-mail (необовязково)')),
                ('phone', models.CharField(max_length=13, verbose_name='Введіть ваш телефон (обовязково)')),
                ('subject', models.TextField(verbose_name='Введіть ваше повідомлення (необовязково)')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
