# Generated by Django 4.2.4 on 2023-09-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0002_remove_contact_phone_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(verbose_name='Дата та час'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Пошта'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Ім^я'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.TextField(verbose_name='Тема запиту'),
        ),
         migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='Телефон'),
        ),
    ]
