# Generated by Django 4.2.4 on 2023-09-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0003_alter_contact_date_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(max_length=100, verbose_name='День та час коли  зателефонувати'),
        ),
    ]
