# Generated by Django 4.2.5 on 2023-10-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0004_alter_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(verbose_name='День та час коли  зателефонувати'),
        ),
    ]
