# Generated by Django 4.2.5 on 2024-06-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0005_alter_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200, verbose_name="Ім'я"),
        ),
    ]
